# Generated by Django 4.1.1 on 2022-09-12 21:19

import django.core.validators
from django.db import migrations, models
import pdf.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pdffile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf",
                    models.FileField(
                        upload_to=pdf.models.set_pdf_file_name,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf"]
                            )
                        ],
                    ),
                ),
                ("filename", models.CharField(max_length=20)),
            ],
        ),
    ]
