# Generated by Django 4.1.1 on 2022-09-12 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pdf", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pdffile",
            name="filename",
        ),
    ]
