# Generated by Django 4.0.2 on 2022-09-20 17:43

import django.core.validators
from django.db import migrations, models
import pdf_gen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdfs', models.FileField(upload_to=pdf_gen.models.set_pdf_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
        ),
    ]
