# Generated by Django 4.0.2 on 2022-09-23 17:46

from django.db import migrations, models
import pdf_gen.models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_gen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='pdfs',
            field=models.FileField(upload_to=pdf_gen.models.set_pdf_file_name),
        ),
    ]
