# Generated by Django 4.0.2 on 2022-09-20 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pdf_gen', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_ref', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('supplier_code', models.IntegerField(null=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('total_invoice_amount', models.FloatField(null=True)),
                ('total_water_rate', models.FloatField(null=True)),
                ('total_water_usage', models.FloatField(null=True)),
                ('total_other_amount', models.FloatField(null=True)),
                ('pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_pdf', to='pdf_gen.file')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_no', models.CharField(max_length=50, null=True)),
                ('meter_type', models.CharField(max_length=50, null=True)),
                ('acc_description', models.CharField(max_length=250, null=True)),
                ('this_reading', models.IntegerField(null=True)),
                ('last_reading', models.IntegerField(null=True)),
                ('consumption', models.IntegerField(null=True)),
                ('average_rate', models.FloatField(null=True)),
                ('other_rate', models.FloatField(null=True)),
                ('consumption_period', models.DateField(blank=True, null=True)),
                ('amount_from_inv', models.FloatField(null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='api.invoice')),
            ],
        ),
    ]
