# Generated by Django 4.0.2 on 2022-09-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_gen', '0001_initial'),
        ('api', '0002_invoice_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_pdf', to='pdf_gen.file'),
        ),
    ]
